### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by fjyl001** [hefengbao/jingmo#26]
建议增加完整包的APP供用户选择下载；
当前需要同步数据版本APP，同步时间太长，不稳定、不利用APP的使用

**Comment by pulasi** [comment]
同意
国内很多用户访问不了 github……下载不到数据，完整版体积大点就大点吧

**Comment by ruoque** [comment]
完全同意！！

**Comment by hefengbao** [comment]
V1.6.0 及之后，扩充了诗文数据，有 1.3 G, 所以数据和应用分开了，需要远程同步数据，使用 Github Pages 搭建的后端服务，理论上大多数人都能访问到才对，这个应该不需要 VPN。

其次 Github/ Gitee 上传的附件有大小限制，打这么大的包，都没法传上来。
