### ISSUE TITLE
1.61 诗文不能同步

### ISSUE THREAD

**Issue by linjinya** [hefengbao/jingmo#30]
V1.61 版本 诗文不能完成同步,10H都不能成功

**Comment by uy-li** [comment]
要用VPN才行

**Comment by hefengbao** [comment]
V1.6.0 及之后，扩充了诗文数据，有 1.3 G, 所以数据和应用分开了，需要远程同步数据，使用 Github Pages 搭建的后端服务，理论上大多数人都能访问到才对，这个应该不需要 VPN。

**Comment by linjinya** [comment]
> V1.6.0 及之后，扩充了诗文数据，有 1.3 G, 所以数据和应用分开了，需要远程同步数据，使用 Github Pages 搭建的后端服务，理论上大多数人都能访问到才对，这个应该不需要 VPN。

可能是打开Github 比较慢,不能同步完成. 数据库能否可以通过电脑下载,再传入手机呢?
