### ISSUE TITLE
作者大大能换一个文件保存位置吗

### ISSUE THREAD

**Issue by uy-li** [hefengbao/jingmo#31]
1.6.1下载的诗词文件在/data/data/com.hefengbao.jingmo/databases/目录下，但是要root才能读写。而且下载的巨慢，作者大大可以把那个下载文件改到/storage/emulated/0/Android/data/这个目录下吗？

**Comment by hefengbao** [comment]
这个数据是从 Github Pages 下载 json 文件，解析后写到数据库的，`/data/data/com.hefengbao.jingmo/databases/` 是 Android 系统设定的。如果你只是需要原始的 json 数据，请看 README.md 中的说明。
