### ISSUE TITLE
APP运行后内容是空的

### ISSUE THREAD

**Issue by bigsinger** [hefengbao/jingmo#54]
![5b6fc17e735b4d1c6c178c24b14300d](https://github.com/hefengbao/jingmo/assets/14847818/09c92f56-041c-457c-8cb6-fe422ba78274)

**Comment by hefengbao** [comment]
#40 这里有说明~

**Comment by bigsinger** [comment]
找到了，给几个建议：

1. 首次运行发现无数据包或无同步过，应该给予一个友情提示，让用户好知道怎么回事、怎么操作。
2. apk可以打一个离线版的数据包在里面，同时也支持同步，如果数据不是最新的则同步。
3. 可以勾选全选进行同步。

@hefengbao
